set nocompatible
set history=100
set ruler
set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%)
filetype plugin indent on
syntax on

" filetype plugin on
set smartindent
set backspace=indent,eol,start
"set hlsearch
set nohls " hlsearch if want highlighting
set showcmd		" display incomplete commands
syntax on
set winminheight=0
set incsearch
set magic
" I dont like tmp vim files, turn them off:
set nobackup
set nowritebackup
set noswapfile
" imap <C-'> <C-]>pi
map <F12> <C-W>_
map <F11> 25<C-W>_
 set matchpairs+=<:>
map <C-k> :tabnext<CR>
" search for a visually selected block
vmap  / y/<C-R>=substitute(escape(@", '\\/.*$^~[]'), "\n", "\\\\n", "g")<CR><CR>
set wildmenu
"Comment lines with ,# or ,/ for C or js type comments
map ,/ :s/^/\/\//<CR> <Esc>:noh<CR>
map ./ :s/^\/\///<CR> <Esc>:noh<CR>
map ,# :s/^/#/<CR> <Esc>:noh<CR>
map .# :s/^#//<CR> <Esc>:noh<CR>
map <C-J> <C-W>x<C-W><Down>
map <Leader># <c-[>'<^r<CR>i/*<c-[>'>$i*/<c-[>
set tabstop=4
set shiftwidth=4
set expandtab
autocmd BufRead *.as setlocal filetype=java
autocmd BufRead *.go setlocal filetype=go
autocmd BufRead *.tt setlocal filetype=php
autocmd BufRead *.pp setlocal filetype=ruby
autocmd BufRead *.ts setlocal filetype=typescript
au BufNewFile,BufRead *.hx set filetype=haxe
set dir=~/.vim/swp
" show matching brackets
autocmd FileType perl setlocal showmatch
colors jellybeans

" check perl code with :make
"autocmd FileType perl set makeprg=perl\ -Ilib\ -c\ %\ $*
autocmd FileType perl setlocal errorformat=%f:%l:%m
autocmd FileType perl setlocal autowrite
autocmd FileType perl setlocal expandtab
autocmd FileType perl setlocal equalprg=perltidy
autocmd FileType go setlocal equalprg=goimports
autocmd FileType html setlocal equalprg=js-beautify\ --type\ html\ -f\ -
autocmd FileType perl setlocal iskeyword+=:
autocmd FileType javascript setlocal iskeyword-=:
autocmd FileType javascript setlocal equalprg=js-beautify\ -f\ -
"autocmd FileType javascript set equalprg=js_beautify.pl\ -
autocmd FileType make set noexpandtab
let perl_include_pod = 1
autocmd FileType set equalprg&
" syntax color complex things like @{${"foo"}}
" One less keypress to enter cmd mode
nnoremap ; :
" gf will now split current file and open the path under the cursor
nnoremap gf :sp<CR>gf
syntax enable
set smartcase
set nofoldenable
set complete-=i
"/*<CR><c-]>'>$i*/<CR>
"show me extraneous whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
"remove trailing whitespace
map ,$ :%s/\s\+$//g<CR>

execute pathogen#infect()

"syntastic
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_go_checkers = ['go', 'gofmt', 'govet', 'errcheck' ]
"let g:syntastic_go_checkers = ['go', 'gofmt', 'golint', 'gotype', 'govet']
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['html','yml'] }
"/syntastic
let g:openssl_backup = 1
