set history=100         " keep 50 lines of command line history
set ruler               " show the cursor position all the time
set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%)
filetype indent on
" filetype plugin on
set smartindent
set bs=2                " allow backspacing over everything in insert mode
set hlsearch
set nohls " hlsearch if want highlighting
syntax on
set winminheight=0
set incsearch
set magic
set nobackup
set nowritebackup
set noswapfile
" imap <C-'> <C-]>pi
map <F12> <C-W>_
map <F11> 25<C-W>_
 set matchpairs+=<:>
map <F6> mzggVG='z
map <C-k> :tabnext<CR>
vmap  / y/<C-R>=substitute(escape(@", '\\/.*$^~[]'), "\n", "\\\\n", "g")<CR><CR>
set wildmenu
imap <C-\.> <C-n>
map ,/ :s/^/\/\//<CR> <Esc>:noh<CR>
map ./ :s/^\/\///<CR> <Esc>:noh<CR>
map ,# :s/^/#/<CR> <Esc>:noh<CR>
map .# :s/^#//<CR> <Esc>:noh<CR>
map \[ gewi[%<Esc>A%]<Esc>
map \{ gewi{<Esc>ea}<Esc>
map \' gewi'<Esc>ea'<Esc>
map \" gewi"<Esc>ea"<Esc>
map \( gewi(<Esc>ea)<Esc>
map <C-J> <C-W>x<C-W><Down>
map <F9> :. s/title="\([^"]\+\)"/[% tooltip("\1") %]/g<CR>:. s/class="tooltip"//g<CR>/tooltip<CR>
"map <C-P> :!pod2html --infile=% --outfile=/home/skaufman/public_html/test.html<CR>
map <leader>1 :!git log --reverse -p -S<cword> %<cr>
vmap gf y:new `pmpath <C-R>"`<CR>
set tabstop=4
set shiftwidth=4
set expandtab
autocmd BufRead *.as set filetype=java
autocmd BufRead *.tt set filetype=php
autocmd BufRead *.pp set filetype=ruby
set dir=~/.vim/swp
"set t_Co=256
"let g:solarized_termcolors=256
colors solarized
set background=dark
    "colorscheme oceanblack 
    "colors darkblue
    "colorscheme mustang 
    "colorscheme symfony 
    "colorscheme clouds-midnight 
    "colorscheme wombat256  
set ttyfast
"set fileencodings=utf-8
"set encoding=utf-8 
"set enc=utf-8
"set fencs=utf-8
" show matching brackets
autocmd FileType perl set showmatch


" check perl code with :make
autocmd FileType perl set makeprg=perl\ -Ilib\ -c\ %\ $*
autocmd FileType perl set errorformat=%f:%l:%m
autocmd FileType perl set autowrite
autocmd FileType perl set expandtab
autocmd FileType perl set equalprg=perltidy
autocmd FileType python set equalprg=pythontidy.py
autocmd FileType perl set iskeyword+=:
autocmd FileType javascript set iskeyword-=:
autocmd FileType javascript set equalprg=js_beautify.pl\ -
autocmd FileType make set noexpandtab
let perl_include_pod = 1
autocmd FileType set equalprg&
" syntax color complex things like @{${"foo"}}
let perl_extended_vars = 1
nnoremap > >>
nnoremap < <<
nnoremap ; :
nnoremap gf :sp<CR>gf
syntax enable
" set background=dark
"inoremap  <Up>     <NOP>
"inoremap  <Down>   <NOP>
"inoremap  <Left>   <NOP>
"inoremap  <Right>  <NOP>
"noremap   <Up>     <NOP>
"noremap   <Down>   <NOP>
"noremap   <Left>   <NOP>
"noremap   <Right>  <NOP>
map [% ggi<CR><C-[>gg"#p"%p:s/.*\/lib\///g<CR>:.s/\//::/g<CR>:.s/\.pm$//g<CR>^ipackage <C-[>A;<CR><C-[>
