set nocompatible
set history=100
set ruler
set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%)
filetype indent on
" filetype plugin on
set smartindent
set backspace=indent,eol,start
"set hlsearch
set nohls " hlsearch if want highlighting
set showcmd		" display incomplete commands
syntax on
set winminheight=0
set incsearch
set magic
set nobackup
set nowritebackup
set noswapfile
" imap <C-'> <C-]>pi
map <F12> <C-W>_
map <F11> 25<C-W>_
 set matchpairs+=<:>
map <C-k> :tabnext<CR>
vmap  / y/<C-R>=substitute(escape(@", '\\/.*$^~[]'), "\n", "\\\\n", "g")<CR><CR>
set wildmenu
map ,/ :s/^/\/\//<CR> <Esc>:noh<CR>
map ./ :s/^\/\///<CR> <Esc>:noh<CR>
map ,# :s/^/#/<CR> <Esc>:noh<CR>
map .# :s/^#//<CR> <Esc>:noh<CR>
map <C-J> <C-W>x<C-W><Down>
map <Leader># <c-[>'<^r<CR>i/*<c-[>'>$i*/<c-[>
set tabstop=4
set shiftwidth=4
set expandtab
autocmd BufRead *.as set filetype=java
autocmd BufRead *.tt set filetype=php
autocmd BufRead *.pp set filetype=ruby
set dir=~/.vim/swp
"set ttyfast
"set fileencodings=utf-8
"set encoding=utf-8 
"set enc=utf-8
"set fencs=utf-8
" show matching brackets
autocmd FileType perl set showmatch
colors jellybeans

" check perl code with :make
"autocmd FileType perl set makeprg=perl\ -Ilib\ -c\ %\ $*
autocmd FileType perl set errorformat=%f:%l:%m
autocmd FileType perl set autowrite
autocmd FileType perl set expandtab
autocmd FileType perl set equalprg=perltidy
autocmd FileType python set equalprg=pythontidy.py
autocmd FileType perl set iskeyword+=:
autocmd FileType javascript set iskeyword-=:
autocmd FileType javascript set equalprg=js_beautify.pl\ -
autocmd FileType make set noexpandtab
let perl_include_pod = 1
autocmd FileType set equalprg&
" syntax color complex things like @{${"foo"}}
nnoremap ; :
nnoremap gf :sp<CR>gf
syntax enable
set smartcase

"/*<CR><c-]>'>$i*/<CR>
